import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {demoDocument} from '../lib/editor/demo';
const owner='11111111-1111-4111-8111-111111111111',editor='22222222-2222-4222-8222-222222222222',viewer='33333333-3333-4333-8333-333333333333',outsider='44444444-4444-4444-8444-444444444444',commenter='55555555-5555-4555-8555-555555555555';
test('PostgreSQL RLS: ownership, roles, immutable history, conflicts, invitations and quotas',async()=>{
 const db=new PGlite();try{await db.exec(`create role authenticated;create role anon;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
 await db.exec(await readFile('supabase/schema.sql','utf8'));
 for(const [id,email] of [[owner,'owner@example.com'],[editor,'editor@example.com'],[viewer,'viewer@example.com'],[outsider,'outside@example.com'],[commenter,'commenter@example.com']])await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,email]);
 const as=async(id:string)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 await as(owner);const created=await db.query<{id:string;revision:number}>('select * from public.pcb_create_project($1::jsonb)',[JSON.stringify(demoDocument())]);const id=created.rows[0].id;assert.equal(created.rows[0].revision,0);
 await db.exec('reset role');for(const [user,role] of [[editor,'editor'],[viewer,'viewer'],[commenter,'commenter']])await db.query('insert into public.pcb_project_members(project_id,user_id,role) values($1,$2,$3)',[id,user,role]);
 await as(outsider);assert.equal((await db.query('select * from public.pcb_projects where id=$1',[id])).rows.length,0);await assert.rejects(db.query('select * from public.pcb_save_project($1,0,$2::jsonb,$3)',[id,JSON.stringify(demoDocument()),'unauthorized']),/Unauthorized/);
 await as(viewer);assert.equal((await db.query('select * from public.pcb_projects where id=$1',[id])).rows.length,1);await assert.rejects(db.query('select * from public.pcb_save_project($1,0,$2::jsonb,$3)',[id,JSON.stringify(demoDocument()),'viewer write']),/Unauthorized/);await assert.rejects(db.query('insert into public.pcb_comments(project_id,author_id,body) values($1,$2,$3)',[id,viewer,'not permitted']),/row-level security/);
 await as(commenter);const comment=await db.query<{id:string}>('insert into public.pcb_comments(project_id,author_id,body) values($1,$2,$3) returning id',[id,commenter,'Please review this connection.']);await db.query('update public.pcb_comments set resolved=true where id=$1',[comment.rows[0].id]);await assert.rejects(db.query('update public.pcb_comments set author_id=$1 where id=$2',[owner,comment.rows[0].id]),/permission denied/);await assert.rejects(db.query('select * from public.pcb_save_project($1,0,$2::jsonb,$3)',[id,JSON.stringify(demoDocument()),'commenter write']),/Unauthorized/);
 await as(editor);const changed=demoDocument();changed.name='Edited by collaborator';const saved=await db.query<{revision:number}>('select * from public.pcb_save_project($1,0,$2::jsonb,$3)',[id,JSON.stringify(changed),'Rename']);assert.equal(saved.rows[0].revision,1);await assert.rejects(db.query('select * from public.pcb_save_project($1,0,$2::jsonb,$3)',[id,JSON.stringify(changed),'stale write']),/revision_conflict/);assert.equal((await db.query('select * from public.pcb_version_changes where project_id=$1',[id])).rows.length,1);await assert.rejects(db.query('delete from public.pcb_version_changes where project_id=$1',[id]),/permission denied/);await assert.rejects(db.query('update public.pcb_projects set owner_id=$1 where id=$2',[editor,id]),/permission denied/);await assert.rejects(db.query('select public.pcb_publish_project($1,true)',[id]),/Unauthorized/);
 await as(owner);await db.query('select public.pcb_publish_project($1,true)',[id]);await db.exec('reset role;set role anon');assert.equal((await db.query('select * from public.pcb_projects where id=$1',[id])).rows.length,1);await assert.rejects(db.query('select public.pcb_save_project($1,1,$2::jsonb,$3)',[id,JSON.stringify(changed),'anon write']),/permission denied/);
 await as(owner);await db.query('select public.pcb_publish_project($1,false)',[id]);for(let i=0;i<2;i++)await db.query('select * from public.pcb_create_project($1::jsonb)',[JSON.stringify(demoDocument())]);await assert.rejects(db.query('select * from public.pcb_create_project($1::jsonb)',[JSON.stringify(demoDocument())]),/Project limit/);
 const tokenHash='a'.repeat(64);await db.query('insert into public.pcb_invitations(project_id,email,role,created_by,token_hash) values($1,$2,$3,$4,$5)',[id,'outside@example.com','editor',owner,tokenHash]);await as(viewer);await assert.rejects(db.query('select public.pcb_accept_invitation($1)',[tokenHash]),/Invitation unavailable/);await as(outsider);const accepted=await db.query<{pcb_accept_invitation:string}>('select public.pcb_accept_invitation($1)',[tokenHash]);assert.equal(accepted.rows[0].pcb_accept_invitation,id);await assert.rejects(db.query('select public.pcb_accept_invitation($1)',[tokenHash]),/Invitation unavailable/);
 const first=await db.query<{pcb_consume_rate_limit:boolean}>("select public.pcb_consume_rate_limit('test',1)");const second=await db.query<{pcb_consume_rate_limit:boolean}>("select public.pcb_consume_rate_limit('test',1)");assert.equal(first.rows[0].pcb_consume_rate_limit,true);assert.equal(second.rows[0].pcb_consume_rate_limit,false);
 const rls=await db.query<{tablename:string;rowsecurity:boolean}>("select tablename,rowsecurity from pg_tables where schemaname='public' and tablename like 'pcb_%'");assert.ok(rls.rows.length>=35);assert.ok(rls.rows.every(t=>t.rowsecurity));}finally{await db.close();}
});
