import type { Part } from "@/types/project";
const pin = (
  id: string,
  name: string,
  type: Part["pins"][number]["type"] = "passive",
  required = true,
) => ({ id, name, type, required });
const baseCatalog: Part[] = [
  {
    id: "esp32",
    name: "ESP32-WROOM-32E",
    category: "Microcontrollers",
    manufacturer: "Espressif",
    mpn: "ESP32-WROOM-32E-N4",
    description: "Wi-Fi + Bluetooth MCU module · 4 MB flash",
    package: "SMD module",
    footprint: "RF_Module:ESP32-WROOM-32E",
    datasheet:
      "https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf",
    price: 3.1,
    stock: null,
    lifecycle: "Unknown",
    pins: [
      pin("1", "3V3", "power"),
      pin("2", "GND", "ground"),
      pin("3", "EN", "input"),
      pin("4", "GPIO21 / SDA", "passive", false),
      pin("5", "GPIO22 / SCL", "passive", false),
      pin("6", "TXD", "output", false),
      pin("7", "RXD", "input", false),
      pin("8", "GPIO2", "output", false),
    ],
    tags: ["wifi", "ble", "mcu"],
  },
  {
    id: "bme280",
    name: "BME280",
    category: "Sensors",
    manufacturer: "Bosch Sensortec",
    mpn: "BME280",
    description: "Humidity, pressure, and temperature sensor",
    package: "LGA-8",
    footprint: "Package_LGA:Bosch_LGA-8_2.5x2.5mm",
    datasheet:
      "https://www.bosch-sensortec.com/products/environmental-sensors/humidity-sensors-bme280/",
    price: 2.65,
    stock: null,
    lifecycle: "Unknown",
    pins: [
      pin("1", "VDD", "power"),
      pin("2", "GND", "ground"),
      pin("3", "SDA", "passive"),
      pin("4", "SCL", "input"),
    ],
    tags: ["temperature", "humidity", "i2c"],
  },
  {
    id: "usb-c",
    name: "USB-C receptacle",
    category: "Connectors",
    manufacturer: "GCT",
    mpn: "USB4105-GF-A",
    description: "USB 2.0 Type-C connector · power input",
    package: "USB-C 16 pin",
    footprint: "Connector_USB:USB_C_Receptacle_GCT_USB4105",
    datasheet: "https://gct.co/connector/usb4105",
    price: 0.72,
    stock: null,
    lifecycle: "Unknown",
    pins: [
      pin("1", "VBUS", "output"),
      pin("2", "GND", "ground"),
      pin("3", "CC1", "passive"),
      pin("4", "CC2", "passive"),
    ],
    tags: ["usb", "connector", "power"],
  },
  {
    id: "ldo",
    name: "AP2112K-3.3",
    category: "Regulators",
    manufacturer: "Diodes Inc.",
    mpn: "AP2112K-3.3TRG1",
    description: "3.3 V low-dropout regulator · 600 mA",
    package: "SOT-25",
    footprint: "Package_TO_SOT_SMD:SOT-23-5",
    datasheet: "https://www.diodes.com/part/view/AP2112",
    price: 0.24,
    stock: null,
    lifecycle: "Unknown",
    pins: [
      pin("1", "VIN", "power"),
      pin("2", "GND", "ground"),
      pin("3", "EN", "input"),
      pin("4", "VOUT", "output"),
    ],
    tags: ["power", "3.3v", "ldo"],
  },
  {
    id: "r10k",
    name: "10 kΩ resistor",
    category: "Resistors",
    manufacturer: "Yageo",
    mpn: "RC0603FR-0710KL",
    description: "10 kΩ · 1% · 0.1 W",
    package: "0603",
    footprint: "Resistor_SMD:R_0603_1608Metric",
    datasheet: "https://www.yageo.com",
    price: 0.01,
    stock: null,
    lifecycle: "Unknown",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["resistor", "pullup"],
  },
  {
    id: "r5k1",
    name: "5.1 kΩ resistor",
    category: "Resistors",
    manufacturer: "Yageo",
    mpn: "RC0603FR-075K1L",
    description: "5.1 kΩ · 1% · USB-C configuration",
    package: "0603",
    footprint: "Resistor_SMD:R_0603_1608Metric",
    datasheet: "https://www.yageo.com",
    price: 0.01,
    stock: null,
    lifecycle: "Unknown",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["usb", "resistor"],
  },
  {
    id: "c100n",
    name: "100 nF capacitor",
    category: "Capacitors",
    manufacturer: "Murata",
    mpn: "GRM188R71C104KA01D",
    description: "100 nF · 16 V · X7R ceramic",
    package: "0603",
    footprint: "Capacitor_SMD:C_0603_1608Metric",
    datasheet: "https://www.murata.com",
    price: 0.02,
    stock: null,
    lifecycle: "Unknown",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["capacitor", "decoupling"],
  },
  {
    id: "c10u",
    name: "10 µF capacitor",
    category: "Capacitors",
    manufacturer: "Murata",
    mpn: "GRM21BR61A106KE19L",
    description: "10 µF · 10 V · X5R ceramic",
    package: "0805",
    footprint: "Capacitor_SMD:C_0805_2012Metric",
    datasheet: "https://www.murata.com",
    price: 0.06,
    stock: null,
    lifecycle: "Unknown",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["capacitor", "power"],
  },
  {
    id: "led",
    name: "Green status LED",
    category: "Diodes",
    manufacturer: "Kingbright",
    mpn: "APT1608SGC",
    description: "Green indicator · 0603",
    package: "0603",
    footprint: "LED_SMD:LED_0603_1608Metric",
    datasheet: "https://www.kingbrightusa.com",
    price: 0.08,
    stock: null,
    lifecycle: "Unknown",
    pins: [pin("1", "A"), pin("2", "K")],
    tags: ["led", "indicator"],
  },
  {
    id: "header",
    name: "Programming header",
    category: "Connectors",
    manufacturer: "Generic",
    mpn: "",
    description: "1 × 4, 2.54 mm UART programming header",
    package: "1x04 P2.54",
    footprint: "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical",
    datasheet: "",
    price: 0.15,
    stock: null,
    lifecycle: "Unknown",
    pins: [
      pin("1", "3V3", "power"),
      pin("2", "GND", "ground"),
      pin("3", "TX", "passive"),
      pin("4", "RX", "passive"),
    ],
    tags: ["uart", "programming"],
  },
];

const genericPart = (config: {
  id: string;
  name: string;
  category: string;
  manufacturer: string;
  mpn: string;
  description: string;
  package: string;
  footprint: string;
  pins: Part["pins"];
  tags: string[];
  price?: number;
}): Part => ({
  ...config,
  datasheet: "",
  price: config.price ?? 0,
  stock: null,
  lifecycle: "Unknown",
});

const additionalCatalog: Part[] = [
  genericPart({
    id: "rp2040",
    name: "RP2040 MCU",
    category: "Microcontrollers",
    manufacturer: "Raspberry Pi",
    mpn: "RP2040",
    description: "Dual-core Arm Cortex-M0+ microcontroller",
    package: "QFN-56",
    footprint: "Package_DFN_QFN:QFN-56-1EP_7x7mm",
    pins: [
      pin("1", "3V3", "power"),
      pin("2", "GND", "ground"),
      pin("3", "RUN", "input"),
      pin("4", "USB_DP", "passive", false),
      pin("5", "USB_DM", "passive", false),
      pin("6", "GPIO0", "passive", false),
      pin("7", "GPIO1", "passive", false),
    ],
    tags: ["mcu", "usb", "arm"],
    price: 1.1,
  }),
  genericPart({
    id: "nrf52840",
    name: "nRF52840 module",
    category: "Microcontrollers",
    manufacturer: "Nordic Semiconductor",
    mpn: "nRF52840-MDK",
    description: "Bluetooth Low Energy 5.0 SoC module",
    package: "SMD module",
    footprint: "RF_Module:nRF52840",
    pins: [
      pin("1", "VDD", "power"),
      pin("2", "GND", "ground"),
      pin("3", "SWDIO", "passive", false),
      pin("4", "SWDCLK", "input", false),
      pin("5", "P0.13", "passive", false),
    ],
    tags: ["ble", "mcu", "wireless"],
    price: 4.8,
  }),
  genericPart({
    id: "stm32g0",
    name: "STM32G031K8T6",
    category: "Microcontrollers",
    manufacturer: "STMicroelectronics",
    mpn: "STM32G031K8T6",
    description: "32-bit Arm Cortex-M0+ MCU",
    package: "UFQFPN-32",
    footprint: "Package_DFN_QFN:UFQFN-32-1EP_5x5mm",
    pins: [
      pin("1", "VDD", "power"),
      pin("2", "VSS", "ground"),
      pin("3", "NRST", "input"),
      pin("4", "PA9", "passive", false),
      pin("5", "PA10", "passive", false),
    ],
    tags: ["mcu", "arm"],
    price: 1.4,
  }),
  genericPart({
    id: "ina219",
    name: "INA219 current monitor",
    category: "Sensors",
    manufacturer: "Texas Instruments",
    mpn: "INA219BIDCNR",
    description: "I2C bus voltage and current monitor",
    package: "SOT-23-8",
    footprint: "Package_TO_SOT_SMD:SOT-23-8",
    pins: [
      pin("1", "VCC", "power"),
      pin("2", "GND", "ground"),
      pin("3", "SDA", "passive"),
      pin("4", "SCL", "input"),
      pin("5", "VIN+", "input"),
      pin("6", "VIN-", "input"),
    ],
    tags: ["i2c", "current", "monitor"],
    price: 1.2,
  }),
  genericPart({
    id: "mpu6050",
    name: "MPU-6050 IMU",
    category: "Sensors",
    manufacturer: "TDK InvenSense",
    mpn: "MPU-6050",
    description: "6-axis accelerometer and gyroscope",
    package: "QFN-24",
    footprint: "Package_DFN_QFN:QFN-24-1EP_4x4mm",
    pins: [
      pin("1", "VDD", "power"),
      pin("2", "GND", "ground"),
      pin("3", "SDA", "passive"),
      pin("4", "SCL", "input"),
      pin("5", "INT", "output", false),
    ],
    tags: ["imu", "i2c", "motion"],
    price: 2.4,
  }),
  genericPart({
    id: "ds18b20",
    name: "DS18B20 temperature sensor",
    category: "Sensors",
    manufacturer: "Analog Devices",
    mpn: "DS18B20Z+",
    description: "1-Wire digital temperature sensor",
    package: "SOIC-8",
    footprint: "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
    pins: [
      pin("1", "GND", "ground"),
      pin("2", "DQ", "passive"),
      pin("3", "VDD", "power"),
    ],
    tags: ["temperature", "1-wire"],
    price: 1.3,
  }),
  genericPart({
    id: "buck-5v",
    name: "MP1584EN buck regulator",
    category: "Regulators",
    manufacturer: "Monolithic Power",
    mpn: "MP1584EN-LF-Z",
    description: "3 A step-down switching regulator",
    package: "QFN-8",
    footprint: "Package_DFN_QFN:QFN-8-1EP_3x3mm",
    pins: [
      pin("1", "VIN", "power"),
      pin("2", "GND", "ground"),
      pin("3", "EN", "input"),
      pin("4", "SW", "output"),
      pin("5", "VOUT", "output"),
    ],
    tags: ["power", "buck", "regulator"],
    price: 0.8,
  }),
  genericPart({
    id: "ltc2950",
    name: "LTC2950 pushbutton on/off",
    category: "Power",
    manufacturer: "Analog Devices",
    mpn: "LTC2950ITS8-2",
    description: "Pushbutton on/off controller",
    package: "TSOT-23-8",
    footprint: "Package_TO_SOT_SMD:TSOT-23-8",
    pins: [
      pin("1", "VIN", "power"),
      pin("2", "GND", "ground"),
      pin("3", "PB", "input"),
      pin("4", "INT", "output", false),
      pin("5", "EN", "output"),
    ],
    tags: ["power", "button"],
    price: 2.1,
  }),
  genericPart({
    id: "esd-usb",
    name: "USB ESD protection array",
    category: "Protection",
    manufacturer: "Nexperia",
    mpn: "PESD5V0X1UL",
    description: "Low-capacitance USB ESD suppressor",
    package: "SOT-353",
    footprint: "Package_TO_SOT_SMD:SOT-353_SC-70-5",
    pins: [
      pin("1", "IO1", "passive"),
      pin("2", "GND", "ground"),
      pin("3", "IO2", "passive"),
      pin("4", "VBUS", "power"),
    ],
    tags: ["esd", "usb", "protection"],
    price: 0.18,
  }),
  genericPart({
    id: "can-transceiver",
    name: "MCP2562 CAN transceiver",
    category: "Interfaces",
    manufacturer: "Microchip",
    mpn: "MCP2562FD-E/SN",
    description: "High-speed CAN FD transceiver",
    package: "SOIC-8",
    footprint: "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
    pins: [
      pin("1", "TXD", "input"),
      pin("2", "GND", "ground"),
      pin("3", "VDD", "power"),
      pin("4", "RXD", "output"),
      pin("5", "CANL", "passive"),
      pin("6", "CANH", "passive"),
      pin("7", "STBY", "input"),
    ],
    tags: ["can", "automotive", "interface"],
    price: 1.4,
  }),
  genericPart({
    id: "rs485",
    name: "MAX3485 RS-485 transceiver",
    category: "Interfaces",
    manufacturer: "Analog Devices",
    mpn: "MAX3485ESA+",
    description: "3.3 V half-duplex RS-485 transceiver",
    package: "SOIC-8",
    footprint: "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
    pins: [
      pin("1", "RO", "output"),
      pin("2", "RE", "input"),
      pin("3", "DE", "input"),
      pin("4", "DI", "input"),
      pin("5", "GND", "ground"),
      pin("6", "A", "passive"),
      pin("7", "B", "passive"),
      pin("8", "VCC", "power"),
    ],
    tags: ["rs485", "interface", "industrial"],
    price: 1.1,
  }),
  genericPart({
    id: "relay",
    name: "5 V signal relay",
    category: "Actuators",
    manufacturer: "Omron",
    mpn: "G5V-1-DC5",
    description: "SPDT low-signal relay",
    package: "Through-hole",
    footprint: "Relay_THT:Relay_SPDT_Omron_G5V-1",
    pins: [
      pin("1", "COIL+", "power"),
      pin("2", "COIL-", "ground"),
      pin("3", "COM", "passive"),
      pin("4", "NO", "passive"),
      pin("5", "NC", "passive"),
    ],
    tags: ["relay", "switch", "actuator"],
    price: 1.9,
  }),
  genericPart({
    id: "button",
    name: "Tactile pushbutton",
    category: "Inputs",
    manufacturer: "C&K",
    mpn: "PTS636 SM43 SMTR LFS",
    description: "Momentary normally-open switch",
    package: "SMD 6 mm",
    footprint: "Button_Switch_SMD:SW_SPST_TL3301",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["button", "switch", "input"],
    price: 0.12,
  }),
  genericPart({
    id: "buzzer",
    name: "3.3 V piezo buzzer",
    category: "Actuators",
    manufacturer: "Murata",
    mpn: "PKMCS0909E4000-R1",
    description: "Small magnetic/piezo sounder",
    package: "SMD",
    footprint: "Buzzer_Beeper:Buzzer_9x9mm",
    pins: [pin("1", "+", "power"), pin("2", "-", "ground")],
    tags: ["buzzer", "audio"],
    price: 0.45,
  }),
  genericPart({
    id: "q-nmos",
    name: "AO3400A N-channel MOSFET",
    category: "Transistors",
    manufacturer: "Alpha & Omega",
    mpn: "AO3400A",
    description: "30 V logic-level N-channel MOSFET",
    package: "SOT-23",
    footprint: "Package_TO_SOT_SMD:SOT-23",
    pins: [
      pin("1", "G", "input"),
      pin("2", "S", "ground"),
      pin("3", "D", "passive"),
    ],
    tags: ["mosfet", "switch", "power"],
    price: 0.08,
  }),
  genericPart({
    id: "q-pmos",
    name: "DMP3010LK P-channel MOSFET",
    category: "Transistors",
    manufacturer: "Diodes Inc.",
    mpn: "DMP3010LK3-13",
    description: "30 V logic-level P-channel MOSFET",
    package: "SOT-23",
    footprint: "Package_TO_SOT_SMD:SOT-23",
    pins: [
      pin("1", "G", "input"),
      pin("2", "S", "power"),
      pin("3", "D", "passive"),
    ],
    tags: ["mosfet", "load-switch", "power"],
    price: 0.12,
  }),
  genericPart({
    id: "zener-5v1",
    name: "5.1 V Zener diode",
    category: "Diodes",
    manufacturer: "onsemi",
    mpn: "BZT52C5V1-7-F",
    description: "SMD 5.1 V voltage clamp",
    package: "SOD-123",
    footprint: "Diode_SMD:D_SOD-123",
    pins: [pin("1", "K", "passive"), pin("2", "A", "ground")],
    tags: ["zener", "clamp", "protection"],
    price: 0.06,
  }),
  genericPart({
    id: "fuse-ptc",
    name: "500 mA resettable fuse",
    category: "Protection",
    manufacturer: "Littelfuse",
    mpn: "1812L050/24DR",
    description: "Polyfuse overcurrent protection",
    package: "1812",
    footprint: "Fuse:Fuse_1812_4532Metric",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["fuse", "protection", "power"],
    price: 0.22,
  }),
  genericPart({
    id: "r1k",
    name: "1 kΩ resistor",
    category: "Resistors",
    manufacturer: "Yageo",
    mpn: "RC0603FR-071KL",
    description: "1 kΩ · 1% · 0.1 W",
    package: "0603",
    footprint: "Resistor_SMD:R_0603_1608Metric",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["resistor", "current-limit"],
    price: 0.01,
  }),
  genericPart({
    id: "r100k",
    name: "100 kΩ resistor",
    category: "Resistors",
    manufacturer: "Yageo",
    mpn: "RC0603FR-07100KL",
    description: "100 kΩ · 1% · 0.1 W",
    package: "0603",
    footprint: "Resistor_SMD:R_0603_1608Metric",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["resistor", "pullup", "pulldown"],
    price: 0.01,
  }),
  genericPart({
    id: "c1u",
    name: "1 µF capacitor",
    category: "Capacitors",
    manufacturer: "Murata",
    mpn: "GRM188R61C105KA12D",
    description: "1 µF · 16 V · X5R ceramic",
    package: "0603",
    footprint: "Capacitor_SMD:C_0603_1608Metric",
    pins: [pin("1", "1"), pin("2", "2")],
    tags: ["capacitor", "decoupling", "power"],
    price: 0.03,
  }),
  genericPart({
    id: "c47u",
    name: "47 µF capacitor",
    category: "Capacitors",
    manufacturer: "Panasonic",
    mpn: "EEE-FK1H470XP",
    description: "47 µF · 50 V low-ESR electrolytic",
    package: "Radial 6.3 mm",
    footprint: "Capacitor_THT:CP_Radial_D6.3mm_P2.50mm",
    pins: [pin("1", "+", "power"), pin("2", "-", "ground")],
    tags: ["capacitor", "bulk", "power"],
    price: 0.22,
  }),
];

export const catalog: Part[] = [...baseCatalog, ...additionalCatalog];
export function searchCatalog(query: string, parts: Part[] = catalog) {
  const q = query.toLowerCase().trim();
  return parts.filter((p) =>
    [
      p.name,
      p.mpn,
      p.manufacturer,
      p.category,
      p.description,
      p.package,
      ...p.tags,
    ]
      .join(" ")
      .toLowerCase()
      .includes(q),
  );
}
